test-ts:
  - all:
      - changed-files:
          - AnyGlobToAnyFile: ["test/**/*.spec.ts"]
chore:
  - all:
      - head-branch: ["^.+/chore-"]
cd:
  - all:
      - AllGlobsToAnyFile: [".github/workflows/.*{yml,yaml}"]
