"scope: extension":
  - all:
      - changed-files:
          - AnyGlobToAnyFile:
              - "test/**/*.spec.{js,ts}"
              - "src/**/*.{js,ts}"
              - ".vscodeignore"
chore:
  - all:
      - head-branch: ["^.+/chore-"]
cd:
  - all:
      - AllGlobsToAnyFile: [".github/workflows/.*{yml,yaml}"]
