name: "pull request title"
# trigger はとりあえず
on:
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - '!v*'

jobs:
  title:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Print title
      run: |
        TYPE="$(grep -o -e '^[^:]\+' <<< "${TITLE}")"
        echo "$(grep -o -e '^[^!]\+' <<< "${TYPE}")"
        if [[ ${TYPE} == *! ]]; then echo "breaking change"; fi
      env:
        TITLE: ${{ github.event.pull_request.title }}