name: "pull request title"
# trigger はとりあえず
on:
  pull_request:
    types:
      - opened
      - edited
  push:
    branches:
      - 'main'
    tags:
      - '!v*'

jobs:
  title:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Print label(check type)
      run: |
        PREFIX="$(grep -o -e '^[^:]\+' <<< "${TITLE}")"
        LABEL="$(grep -o -e '^[^(!]\+' <<< "${PREFIX}")"
        echo "label(type): ${LABEL}"
        SCOPE="$(sed -e 's/[^(]\+(\([^)]\+\).\+/\1/' <<< "${LABEL}")"
        echo "scope: ${SCOPE}"
        if [[ ${PREFIX} == *! ]]; then echo "breaking change"; fi

        TYPES=("fix" "feat" "build" "chore" "ci" "docs" "style" "refactor" "perf" "test")
        for i in ${TYPES[@]}; do
            if [[ "${i}" = "${LABEL}" ]]; then
                exit 0
            fi
        done
        exit 1
      env:
        TITLE: ${{ github.event.pull_request.title }}