name: "pull request title"
# trigger はとりあえず
on:
  pull_request:
    types:
      - opened
      - edited
  push:
    branches:
      - 'main'
    tags:
      - '!v*'

jobs:
  title:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - id: info
      uses: ./.github/actions/sem-title
      with:
        TITLE: ${{ github.event.pull_request.title }}

    - name: Print label(check type)
      run: |
        gh pr edit --add-label "${LABEL}" -R "${REPO}" "${PR_NUM}"

        gh pr view  --json labels --jq '.labels[].name' -R "${REPO}" "${PR_NUM}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TYPE: ${{ steps.info.outputs.type }}
        REPO: ${{ github.repository }}
        PR_NUM: ${{ github.event.pull_request.number }}
      shell: bash
  