name: "pull request title"
# trigger はとりあえず
on:
  pull_request:
    types:
      - opened
      - edited
  push:
    branches:
      - 'main'
    tags:
      - '!v*'

jobs:
  title:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - id: info
      name: info
      uses: ./.github/actions/sem-title
      with:
        TITLE: ${{ github.event.pull_request.title }}

    - name: edit
      uses: ./.github/actions/sem-to-label
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        repo: ${{ github.repository }}
        pr-num: ${{ github.event.pull_request.number }}
        type: ${{ steps.info.outputs.type }}
        is-breaking-change: ${{ steps.info.outputs.is_breaking_change }}
  