name: "pull request title"
# trigger はとりあえず
on:
  pull_request:
    types:
      - opened
      - edited
  push:
    branches:
      - 'main'
    tags:
      - '!v*'

jobs:
  title:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Print label(check type)
      run: |
        PREFIX="$(grep -o -e '^[^:]\+' <<< "${TITLE}")"

        LABEL="$(grep -o -e '^[^(!]\+' <<< "${PREFIX}")"
        echo "label(type): ${LABEL}"

        SCOPE="$(grep  -o -e '([^)]\+' <<< "${PREFIX}" || echo '')"
        SCOPE="${SCOPE#(}"
        echo "scope: ${SCOPE}"

        echo -n "breaking change: "
        if [[ ${PREFIX} == *! ]]; then echo "true"; else echo "false"; fi

        TYPES=("fix" "feat" "build" "chore" "ci" "docs" "style" "refactor" "perf" "test")
        for i in ${TYPES[@]}; do
            if [[ "${i}" = "${LABEL}" ]]; then
                break
            fi
        done
        exit 1

        gh pr edit --add-label "${LABEL}" -R "${REPO}" "${PR_NUM}"

        gh pr view  --json labels --jq '.labels[].name' -R "${REPO}" "${PR_NUM}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TITLE: ${{ github.event.pull_request.title }}
        REPO: ${{ github.repository }}
        PR_NUM: ${{ github.event.pull_request.number }}
      shell: bash
  